### ISSUE TITLE
category names

### ISSUE THREAD

**Issue by evilnick** [lvoytek/discourse-triage#17]
Hi, many thanks for this tool!
I did have a bit of difficulty getting it to work because I use a weird non-canonical discourse

so 
```

dsctriage -s https://discuss.kubernetes.io -c 'general discussions'

Discourse Comment Triage Helper
Showing comments belonging to the general discussions category on https://discuss.kubernetes.io, updated on 2023-06-12 (Monday)
Problem with Kubernetes G… [Farul Putraa] 
└─ +40340 [Raman Gupta, 2023-06-12] 
*CIS cluster hardening [Konstantinos Tsakalozos, 2023-06-12] 
+CIS hardening and assesm… [Konstantinos Tsakalozos, 2023-06-12] 
Pull image from nexus 3 g… [KEN] 
└─ +40331 [Vinoth, 2023-06-12] 
```
works, but what I really want is the subcategory - https://discuss.kubernetes.io/c/general-discussions/microk8s/26

Sorry I haven't had time to look at the code but i wonder if it might be an idea to allow selecting the category by its id number - I think that may solve the problem

**Comment by lvoytek** [comment]
Thanks for the report! I'll try and add subcategories as an option through something like 

`dsctriage -s https://discuss.kubernetes.io -c 'general discussions/microk8s'`

Search by id is also a good idea so I'll implement that too

**Comment by lvoytek** [comment]
Just finished adding the ability to check subcategories with `/`, such as -c 'general discussions/microk8s'. This should be available on the `edge` channel of the snap in the next few minutes. It'll be added to `stable` in version 1.6.0.
